-- Copy/paste SQL for the existing Supabase database shown in the prompt.
-- Adds the schema needed by Enterprise plan-limit messaging.
-- Safe to run more than once.

-- Existing production schema shown in the prompt is missing this column, while
-- the current identify/users code reads and writes end_users.properties.
ALTER TABLE public.end_users
  ADD COLUMN IF NOT EXISTS properties jsonb;

-- New table for email sends suppressed because a tenant reached the monthly
-- Enterprise email limit.
CREATE TABLE IF NOT EXISTS public.suppressed_emails (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL,
  end_user_id uuid NOT NULL,
  step character varying(100) NOT NULL,
  reason character varying(100) NOT NULL DEFAULT 'email_limit_reached'::character varying,
  suppressed_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppressed_emails_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT suppressed_emails_end_user_id_fkey
    FOREIGN KEY (end_user_id) REFERENCES public.end_users(id)
);

CREATE INDEX IF NOT EXISTS suppressed_emails_tenant_id_idx
  ON public.suppressed_emails USING btree (tenant_id);

CREATE INDEX IF NOT EXISTS suppressed_emails_end_user_id_idx
  ON public.suppressed_emails USING btree (end_user_id);

CREATE INDEX IF NOT EXISTS suppressed_emails_tenant_suppressed_at_idx
  ON public.suppressed_emails USING btree (tenant_id, suppressed_at DESC);
