
// auth.js - Generated by OnboardFlow
const express = require('express');
const router = express.Router();

// You would run: npm install onboardflow
// const { OnboardFlow } = require('onboardflow'); 

// MOCKING THE SDK FOR NOW (Since we haven't published to NPM yet)
class OnboardFlow {
    constructor(key) { this.key = key; }
    async identify(data) { 
        console.log("Simulating SDK Call with key:", this.key, data);
        // In real life, this calls the API
    }
}

// CONFIG
const client = new OnboardFlow("obf_live_e5a356cd34d48dd7f2a87a8d54fbe7e3d143c10f3496b6a0");

// 1. LOGIN ROUTE (Magic Link)
router.post('/login', async (req, res) => {
  const { email } = req.body;
  
  try {
     // LOOK HOW CLEAN THIS IS NOW:
     await client.identify({ userId: email, email: email });
     
     return res.json({ success: true, message: "Magic link sent" });
  } catch (e) {
     return res.status(500).json({ error: "Error" });
  }
});

module.exports = router;
