const { intro, outro, select, text, spinner } = require('@clack/prompts');
const fs = require('fs');
const path = require('path');

async function main() {
  console.clear();
  intro(`🚀 OnboardFlow Setup Wizard`);

  // 1. Ask the Developer what stack they use
  const stack = await select({
    message: 'Which stack are you using?',
    options: [
      { value: 'mern', label: 'MERN (Express + MongoDB)' },
      { value: 'next', label: 'Next.js (App Router)' },
    ],
  });

  if (stack === 'mern') {
    // 2. MERN Setup
    const apiKey = await text({
      message: 'Paste your OnboardFlow API Key:',
      placeholder: 'obf_...',
      validate: (value) => {
        if (!value) return 'Please enter an API Key.';
      }
    });

    const s = spinner();
    s.start('Generating Auth Module...');

    // 3. THE MAGIC: This is the pre-written Auth Code we give them
    // 3. THE MAGIC: Clean Code using SDK
    const authTemplate = `
// auth.js - Generated by OnboardFlow
const express = require('express');
const router = express.Router();

// You would run: npm install onboardflow
// const { OnboardFlow } = require('onboardflow'); 

// MOCKING THE SDK FOR NOW (Since we haven't published to NPM yet)
class OnboardFlow {
    constructor(key) { this.key = key; }
    async identify(data) { 
        console.log("Simulating SDK Call with key:", this.key, data);
        // In real life, this calls the API
    }
}

// CONFIG
const client = new OnboardFlow("${apiKey}");

// 1. LOGIN ROUTE (Magic Link)
router.post('/login', async (req, res) => {
  const { email } = req.body;
  
  try {
     // LOOK HOW CLEAN THIS IS NOW:
     await client.identify({ userId: email, email: email });
     
     return res.json({ success: true, message: "Magic link sent" });
  } catch (e) {
     return res.status(500).json({ error: "Error" });
  }
});

module.exports = router;
`;

    // 4. Write the file to their disk
    fs.writeFileSync('auth.js', authTemplate);
    
    // Simulate a delay for effect
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    s.stop('Generated "auth.js" successfully!');
    
    outro(`You're all set! \n1. Run "npm install node-fetch" \n2. Import this router in your server.js`);
  } else {
    outro('Next.js generator coming soon!');
  }
}

main();