-- Adds Enterprise plan-limit suppression logging to the existing Supabase schema.
-- The provided production schema already has tenants, end_users, and email_usage.
-- It does not yet have suppressed_emails.

CREATE TABLE IF NOT EXISTS public.suppressed_emails (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL,
  end_user_id uuid NOT NULL,
  step character varying(100) NOT NULL,
  reason character varying(100) NOT NULL DEFAULT 'email_limit_reached'::character varying,
  suppressed_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppressed_emails_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT suppressed_emails_end_user_id_fkey
    FOREIGN KEY (end_user_id) REFERENCES public.end_users(id)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS suppressed_emails_tenant_id_idx
  ON public.suppressed_emails USING btree (tenant_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS suppressed_emails_end_user_id_idx
  ON public.suppressed_emails USING btree (end_user_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS suppressed_emails_tenant_suppressed_at_idx
  ON public.suppressed_emails USING btree (tenant_id, suppressed_at DESC);
